version: "3.7"
services:
  backend:
    container_name: backendIngSoft2
    build: #se puede poner solo el punto si el archivo se llama dockerfile
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:5001" # puerto fisico VS puerto del contenedor
    networks:
      - processor-net
  redis:
    image: redis:7.2.1 # Usa la imagen oficial de Redis
    container_name: redisIngSoft2
    ports:
      - "6379:6379" # Mapea el puerto de Redis
    networks:
      - processor-net
  minio:
    container_name: minio
    image:  minio/minio:RELEASE.2021-07-12T02-44-53Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:	
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 123minio321
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["cmd", "curl","-f", "http://localhost:9000/minio/health/live"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  processor-net:
    driver: bridge

volumes:
  minio_storage: {}
    