name: code workflow
on:
  push:
    branches:
      -main
      -dev
jobs:
  code-validation:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Review files
        run: ls